---
- name: Include server preparation tasks
  ansible.builtin.import_tasks: prepare.yml
  tags: ['never', 'prep']
# - name: Include deployment tasks
#   ansible.builtin.import_tasks: deploy.yml
#   tags: ['arr']
