- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: full
    autoclean: yes
    autoremove: yes

- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - ufw
    state: present

# UFW Configuration
- name: Configure UFW defaults
  ufw:
    direction: '{{ item.direction }}'
    policy: '{{ item.policy }}'
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Configure UFW rules
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 22 # SSH
    - 8989 # Sonarr
    - 7878 # Radarr
    - 8686 # Lidarr
    - 9696 # Prowlarr
    - 8080 # Sabnzbd

- name: Enable UFW
  ufw:
    state: enabled
  async: 1
  poll: 0
